project:
  type: website

website:
  title: "Data Hacking with Hackworth"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/bridg3r
format:
  html:
    theme: cosmo
    css: styles.css



